myblog/blog/urls.py
from django.conf.urls import url
from.import views
app_name = 'blog'
urlpatterns = [
    url(r'^$',views.index, name='index'),
    url(r'^detail/(\d+)$', views.detail, name='detail'),
    url(r'^achives/(\d+)/(\d+)$', views.achives, name='achives'),
    url(r'^category/(\d+)$', views.category, name='category'),
    url(r'^tag/(\d+)$', views.tag, name='tag'),
    # url(r'^rss/$',PostFeed(), name='rss'),
]

myblog/comment/urls.py
from django.conf.urls import url
from . import views
app_name = 'comment'

urlpatterns = [
    url(r'^commitcomment/(\d+)/$', views.commitcomment, name='commitcomment'),
]

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
urlpatterns = [
    path('admin/', admin.site.urls),
    url('blog/', include('blog.urls', namespace='blog')),
    url('blog/', include('comment.urls', namespace='comment')),
]

myblog/blog/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Category(models.Model):
    name = models.CharField('名称', max_length=30)

    class Meta:
        verbose_name = '类别'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField('名称', max_length=100)

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField('标题', max_length=10)
    summary = models.CharField('摘要', max_length=100)
    body = models.TextField('内容')
    views = models.PositiveIntegerField('阅读量', default=0)
    create_time = models.DateTimeField('发布时间', auto_now_add=True)
    modeified_time = models.DateTimeField('修改时间', auto_now_add=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='类别')
    tags = models.ManyToManyField(Tag, verbose_name='标签')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='作者')

    class Meta:
        verbose_name = '博客'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title

    # def increseview(self):
    #     self.views += 1
    #     self.save()

myblog/comment/models.py
from django.db import models
from blog.models import Post
# Create your models here.


class Comment(models.Model):
    name = models.CharField('名字', max_length=20)
    email = models.EmailField(blank=True, null=True)
    url = models.URLField(blank=True,null=True)
    text = models.TextField()
    create_time = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

myblog/comment/forms.py
from django.forms import ModelForm
from .models import Comment


class CommentForm(ModelForm):
    class Meta():
        model = Comment
        fields = ['name', 'email', 'url', 'text']

myblog/blog/views.py
from django.shortcuts import render,get_list_or_404,get_object_or_404
from .models import Category,Tag,Post
from comment.forms import CommentForm
# Create your views here.


def index(request):
    postlist = Post.objects.all()
    context = {
        'postlist': postlist
    }
    return render(request, 'blog/index.html', context)


def detail(request, id):
    post = get_object_or_404(Post,pk=id)
    post.views += 1
    post.save()
    context = {
        'post': post,
        'form': CommentForm(),
    }
    return render(request,'blog/single.html', context)


def achives(request,y,m):
    postlist = get_object_or_404(Post,create_time_year=y, create_time_month=m)
    context = {
        'postlist':postlist
    }
    return render(request, 'blog/index.html', context)


def category(request):
    postlist = get_object_or_404(Category,pk=id).post_set.all()
    context = {
        'postlist':postlist
    }
    return render(request, 'blog/index.html', context)


def tag(request):
    postlist = get_object_or_404(Tag, pk=id).post_set.all()
    context = {
        'postlist':postlist
    }
    return render(request, 'blog/index.html', context)

myblog/comment/views.py
from django.shortcuts import render,get_object_or_404,redirect,HttpResponse,reverse
from blog.models import Post
from .forms import CommentForm
# Create your views here.


def commitcomment(request, id):
    post = get_object_or_404(Post, pk=id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect(reverse('blog:detail', args=(id,)))
        else:
            return HttpResponse('评论失败')

    else:
        return HttpResponse('评论失败')

myblog/templates/blog/base.html
{% load extend_fun %}
<!DOCTYPE html>
<html>
<head>
    <title>Black &amp; White</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="/static/css/pace.css">
    <link rel="stylesheet" href="/static/css/custom.css">

    <!-- js -->
    <script src="/static/js/jquery-2.1.3.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/pace.min.js"></script>
    <script src="/static/js/modernizr.custom.js"></script>
</head>

<body>
    <div class="container">
        <header id="site-header">
            <div class="row">
                <div class="col-md-4 col-sm-5 col-xs-8">
                    <div class="logo">
                        <h1><a href="/blog/"><b>Black</b> &amp; White</a></h1>
                    </div>
                </div><!-- col-md-4 -->
                <div class="col-md-8 col-sm-7 col-xs-4">
                    <nav class="main-nav" role="navigation">
                        <div class="navbar-header">
                            <button type="button" id="trigger-overlay" class="navbar-toggle">
                                <span class="ion-navicon"></span>
                            </button>
                        </div>

                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="nav navbar-nav navbar-right">
                                <li class="cl-effect-11"><a href="index.html" data-hover="首页">首页</a></li>
                                <li class="cl-effect-11"><a href="full-width.html" data-hover="博客">博客</a></li>
                                <li class="cl-effect-11"><a href="about.html" data-hover="关于">关于</a></li>
                                <li class="cl-effect-11"><a href="contact.html" data-hover="联系">联系</a></li>
                            </ul>
                        </div><!-- /.navbar-collapse -->
                    </nav>
                    <div id="header-search-box">
                        <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                        <div id="search-form" class="search-form">
                            <form role="search" method="get" id="searchform" action="#">
                                <input type="search" placeholder="搜索" required>
                                <button type="submit"><span class="ion-ios-search-strong"></span></button>
                            </form>
                        </div>
                    </div>
                </div><!-- col-md-8 -->
            </div>
        </header>
    </div>
    <div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
    <div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div>

    <div class="content-body">
        <div class="container">
            <div class="row">
                <main class="col-md-8">
                    {% block left %}

                    {% endblock %}
                </main>
                <aside class="col-md-4">
                    {% block toc %}

                    {% endblock %}
                    <div class="widget widget-recent-posts">
                        <h3 class="widget-title">最新文章</h3>
                        <ul>
                            {% getlatestposts as latestpost %}
                            {% for post in latestpost %}
                            <li>
                                <a href="{% url 'blog:detail' post.id %}">{{post.title}}</a>
                            </li>
                            {% empty %}
                                <li>没有新文章</li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="widget widget-archives">
                        <h3 class="widget-title">归档</h3>
                        <ul>
                            {% getdatelist as datelist %}
                            {% for date in datelist %}
                            <li>
                                <a href="{% url 'blog:achives' date.year date.month %}">{{date.year}}年{{date.month}}月</a>
                            </li>
                            {% empty %}
                                <li>没有归档</li>
                            {% endfor %}
                        </ul>
                    </div>

                    <div class="widget widget-category">
                        <h3 class="widget-title">分类</h3>
                        <ul>
                            {% getcatgory as categorys %}
                            {% for category in categorys %}
                            <li>
                                <a href="{% url 'blog:category' category.id %}">{{category.name}}<span class="post-count">{{category.post_set}}</span></a>
                            </li>
                            {% empty %}
                                <li>没有分类</li>
                            {% endfor %}
                        </ul>
                    </div>

                    <div class="widget widget-tag-cloud">
                        <h3 class="widget-title">标签云</h3>
                        <ul>
                            {% gettags as tags %}
                            {% for tag in tags %}
                            <li>
                                <a href="{% url 'blog:tag' tag.id %}">{{tag.name}}</a>
                            </li>
                            {% empty %}
                                <li>没有标签</li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="rss">
                        <a href="#"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                    </div>
                </aside>
            </div>
        </div>
    </div>
    <footer id="site-footer">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <p class="copyright">&copy 2017 - 采集自<a href="http://www.cssmoban.com/"
                                                            target="_blank" title="模板之家">模板之家</a>
                        - 由<a href="http://zmrenwu.com/" title="网页模板" target="_blank">追梦人物的博客</a>修改
                    </p>
                </div>
            </div>
        </div>
    </footer>

    <!-- Mobile Menu -->
    <div class="overlay overlay-hugeinc">
        <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
        <nav>
            <ul>
                <li><a href="index.html">首页</a></li>
                <li><a href="full-width.html">博客</a></li>
                <li><a href="about.html">关于</a></li>
                <li><a href="contact.html">联系</a></li>
            </ul>
        </nav>
    </div>

    <script src="/static/js/script.js"></script>

</body>
</html>

myblog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% load extend_fun %}
{% block left %}
    {% for post in postlist %}
        <article class="post post-1">
            <header class="entry-header">
                <h1 class="entry-title">
                    <a href="{% url 'blog:detail' post.id%}">{{post.title}}</a>
                </h1>
                <div class="entry-meta">
                    <span class="post-category"><a href="{% url 'blog:category' post.category.pk %}">{{post.category.name}}</a></span>
                    <span class="post-date"><a href="#"><time class="entry-date"
                                                              datetime="{{post.create_time}}">{{post.create_time}}</time></a></span>
                    <span class="post-author"><a href="#">{{post.author.username}}</a></span>
                    <span class="comments-link"><a href="{% url 'blog:detail' post.id %}#comment-area">{{post.comment_set.count}} 评论</a></span>
                    <span class="views-count"><a href="{% url 'blog:detail' post.id %}">{{post.views}}阅读量</a></span>
                </div>
            </header>
            <div class="entry-content clearfix">
                <p>{{post.body|slice:'100'}}...</p>
                <div class="read-more cl-effect-14">
                    <a href="{% url 'blog:detail' post.id %}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                </div>
            </div>
        </article>
    {% empty %}
        没有文章
    {% endfor %}
{% endblock%}

myblog/templates/blog/single.html
{% extends 'blog/base.html '%}
{% load extend_fun %}

{% block left %}
        <article class="post post-1">
            <header class="entry-header">
                <h1 class="entry-title">{{post.title}}</h1>
                <div class="entry-meta">
                    <span class="post-category"><a href="#">{{post.category.name}}</a></span>
                    <span class="post-date"><a href="#"><time class="entry-date"
                                                              datetime="{{comment.create_time}}">{{post.create_time}}</time></a></span>
                    <span class="post-author"><a href="#">{{post.author.username}}</a></span>
                    <span class="comments-link">
                        <a href="{% url 'blog:detail' post.id %}#comment-area">{{post.comment_set.count}}评论</a></span>
                    <span class="views-count"><a href="{% url 'blog:detail' post.id %}">{{post.views}} 阅读量</a></span>
                </div>
            </header>
            <div class="entry-content clearfix">
                <p>
                    {{post.body|safe}}
                </p>
            </div>
        </article>
        <section class="comment-area" id="comment-area">
                    <hr>
                    <h3>发表评论</h3>
                        <form action="{% url 'comment:commitcomment' post.id %}" method="post" class="comment-form">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-4">
                                    <label for="{{form.name.id_for_label}}">名字：</label>
                                    {{form.name}}
                                </div>
                                <div class="col-md-4">
                                    <label for="{{form.email.id_for_label}}">邮箱：</label>
                                    {{form.email}}
                                </div>
                                <div class="col-md-4">
                                    <label for="{{form.url.id_for_label}}">网址：</label>
                                    {{form.url}}
                                </div>
                                <div class="col-md-12">
                                    <label for="{{form.text.id_for_label}}">评论：</label>
                                    {{form.text}}
                                    <button type="submit" class="comment-btn">发表</button>
                                </div>
                            </div>
                           <!-- row -->
                        </form>
                    <div class="comment-list-panel">
                        <h3>评论列表，共 <span>{{post.comment_set.all.count}}</span> 条评论</h3>
                        <ul class="comment-list list-unstyled">
                                <li class="comment-item">
                                    <span class="nickname">{{comment.name}}</span>
                                    <time class="submit-date" datetime="{{comment.create_time}}">{{comment.create_time}}</time>
                                    <div class="text">
                                       {{comment.text}}
                                    </div>
                                </li>
                        </ul>
                    </div>
                </section>

{% endblock %}
{% block toc %}
<div class="widget widget-content">
                    <h3 class="widget-title">文章目录</h3>
                    {{post.toc|safe}}
                </div>
{% endblock %}