tian/booktest/urls.py
from django.conf.urls import url
from .import views

app_name = "booktest"
urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^list/$', views.list, name='list'),
    url(r'^detail/(\d+)/$', views.detail, name='detail'),
    url(r'^delete/(\d+)/$', views.delete, name='delete'),
    url(r'^addhero/(\d+)/$',views.addhero, name='addhero'),
    url(r'^addherohandler/(\d+)/$', views.addherohandler, name='addherohandler'),
    url(r'^area/$', views.area, name='area'),
]

tian/tian/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url('booktest/', include('booktest.urls')),
]

tian/booktest/models.py
from django.db import models

# Create your models here.


class BookInfo(models.Model):
    btitle = models.CharField(max_length=20)
    bpub_date = models.DateTimeField()

    def __str__(self):
        return self.btitle


class HeroInfo(models.Model):
    hname = models.CharField(max_length=20)
    hgender = models.BooleanField()
    hcontent = models.CharField(max_length=50)
    hBook = models.ForeignKey("BookInfo", on_delete=models.CASCADE)

    def __str__(self):
        return self.hname

    def name(self):
        return self.hname
    name.short_desciption = "姓名"

    def skill(self):
        return self.hcontent
    skill.short_desciption = "功法"

    def sex(self):
        return self.hgender
    sex.short_desciption = "性别"


class Area(models.Model):
    title = models.CharField(max_length=30)
    parentarea = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.title

tian/booktest/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from .models import BookInfo,HeroInfo, Area
from django.template import loader
# Create your views here.
#
#
# def index(request):
#     # return HttpResponse('首页')
#     # indextem = loader.get_template('booktest/index.html')
#     # cont = {'username': 'tyy'}
#     # result = indextem.render(cont)
#     # return HttpResponse(result)
#     return render(request, 'booktest/index.html', {'username': 'tyy'})
#
#
# def list(request):
#     # return HttpResponse('列表页')
#     b1 = BookInfo.objects.all()
#     return render(request, 'booktest/list.html', {'booklist': b1})
#
#
# def detail(request, id):
#     # try:
#     #     book = BookInfo.objects.get(pk=int(id))
#     #     return HttpResponse(book)
#     # except:
#     #     return HttpResponse('id错误')
#     book = BookInfo.objects.get(pk=id)
#     return render(request, 'booktest/detail.html', {'book':book})
# ============


def index(request):
    return render(request,'booktest/index.html', {'username': "田元元"})


def list(request):
    b1 = BookInfo.objects.all()
    return render(request,'booktest/list.html', {'booklist': b1})


def detail(request, id):
    book = BookInfo.objects.get(pk=id)
    return render(request,'booktest/detail.html', {'book': book})


def delete(request, id):
    try:
        BookInfo.objects.get(pk=id).delete()
        b1 = BookInfo.objects.all()
        return render(request, 'booktest/list.html', {'booklist': b1})
    except:
        print("删除失败")


def addhero(request, bookid):
    try:
        return render(request, 'bookteset/addhero.html',{'bookid': bookid})

    except:
        return HttpResponse("添加失败")


def addherohandler(request,bookid):
    try:
        bookid = request.POST('bookid')
        hname = request.POST('heroname')
        hgender = request.POST('sex')
        hcontent = request.POST('herocontent')

        book = BookInfo.objects.get(pk=bookid)
        hero = HeroInfo()
        hero.hname = hname
        hero.hgender = True
        hero.hcontent = hcontent
        hero.hBook = book
        hero.save()
        return HttpResponse('/booktest/detail'+str(bookid)+'/',{'book':'book'})
    except:
        return HttpResponse("添加失败")


def area(request):
    area = Area.objects.get(pk=3)
    return render(request, 'booktest/area.html', {'area':area})

tian/templates/booktest/addhero.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加</title>
    {#<link rel="stylesheet" href="/static/css/main.css">#}
</head>
</head>
<body>
    <h2>添加角色</h2>
    角色名：<input type="text" name="heroname">
    <br>
    性别：男 <input type="radio" value="1" name="sex" checked> 女 <input type="radio" value="0">
    绝招: <input type="text">
    <br>
    <input type="hidden" value="{{bookid}}" name="bookid">
    <input type="submit" value="添加" name="herocontent">


</body>
</html>

tian/templates/booktest/area.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>地区</title>
</head>
<body>
    <select name="" id="">
        <option value="">当前地区：{{area.title}}</option>
        <option value="">安阳</option>
        <option value="">保定</option>
    </select>
    <br>
    上级行政区：{{area.parentarea.title}}
    <br>
    下属区域：
        <ul>
            {% for a in area.area_set.all%}
                <li>{{a.title}}</li>
            {% empty%}
                <li>不存在</li>
            {% endfor %}
        </ul>
</body>
</html>

tian/templates/booktest/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>详情页</title>
    {#<link rel="stylesheet" href="/static/css/main.css">#}
</head>
<body>
   <h2>{{book.btitle}}</h2>
    <ul>
        {% for hero in book.heroinfo_set.all %}
            <li>{{book.name}}----{{book.skill}}</li>
        {% empty %}
            <h3>没有角色信息</h3>
        {% endfor%}
    </ul>
   <a href="{% url 'booktest:addhero' book.id %}">添加角色</a>
   <br>
   <a href="{% url 'booktest:list' %}">返回列表页</a>
</body>
</html>

tian/templates/booktest/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
    <!--<link rel="stylesheet" href="/static/css/main.css">-->
</head>
<body>
   {% if username %}
    <h1>{{username}}</h1>
   {% else %}
        <h1>没有此用户</h1>
   {% endif%}
   <a href="{% url 'booktest:list' %}">进入列表页</a>
</body>
</html>

tian/templates/booktest/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>列表页</title>
    {#<link rel="stylesheet" href="/static/css/main.css">#}
</head>
<body>
   <h1>书籍信息</h1>
    <ul>
        {% for book in booklist %}
            <li><a href="{% url 'booktest:detail' book.id%}">{{book.btitle}}</a></li>
            <a href="{% url 'booktest:delete' book.id%}">删除</a>
        {% empty %}
            <h3>没有图书信息</h3>
        {% endfor %}
    </ul>
    <a href="{% url 'booktest:index' %}">返回首页</a>
</body>
</html>